name = "Lord Percy"
license = "MIT"
licenselink = "https://github.com/alexjj/lord-percy/blob/master/LICENSE.md"
description = "Lord Percy is rather simple, but quite attractive. A minimal theme for your site. Forked from the Xtremely minimal theme by Yihui Xui."
homepage = "https://github.com/alexjj/lord-percy"
tags = ["minimal", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "Alex Johnstone"
  homepage = "https://alexjj.com"

[original]
  author = "Yihui Xui"
  homepage = "https://xmin.yihui.name/"
repo = "https://github.com/yihui/hugo-xmin"
